# Auto-generated by InfraPilot
terraform {
  backend "s3" {
    bucket = "terraform-state"
    key    = "infrapilot/terraform.tfstate"
    region = "us-east-1"

    endpoints = {
      s3 = "http://localhost:4566"
    }

    access_key                  = "test"
    secret_key                  = "test"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_requesting_account_id  = true
    force_path_style            = true
  }
}

# Antes de rodar terraform init, crie o bucket no LocalStack:
# aws --endpoint-url=http://localhost:4566 s3 mb s3://terraform-state

provider "aws" {
  region                      = var.aws_region
  access_key                  = "test"
  secret_key                  = "test"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    ec2            = "http://localhost:4566"
    s3             = "http://localhost:4566"
    rds            = "http://localhost:4566"
    iam            = "http://localhost:4566"
    lambda         = "http://localhost:4566"
    dynamodb       = "http://localhost:4566"
    sqs            = "http://localhost:4566"
    sns            = "http://localhost:4566"
    kinesis        = "http://localhost:4566"
    cloudwatch     = "http://localhost:4566"
    cloudwatchlogs = "http://localhost:4566"
    route53        = "http://localhost:4566"
    apigateway     = "http://localhost:4566"
    eks            = "http://localhost:4566"
    elb            = "http://localhost:4566"
    elbv2          = "http://localhost:4566"
  }
}

# Workspaces:
#   terraform workspace new dev
#   terraform workspace new tst
#   terraform workspace new prd
#   terraform workspace select dev   # então: terraform plan -var-file=dev.tfvars

module "v1" {
  source = "./modules/v1"
  name                 = "${terraform.workspace}-vpc_principal"
  cidr_block           = "10.0.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true
  instance_tenancy     = "default"
  environment          = terraform.workspace
}

module "sn_pub_1" {
  source = "./modules/sn_pub_1"
  name                    = "${terraform.workspace}-subnet_public_1"
  vpc_id                  = module.v1.vpc_id
  cidr_block              = "10.0.1.0/24"
  map_public_ip_on_launch = false
  environment             = terraform.workspace
}

module "sn_pub_2" {
  source = "./modules/sn_pub_2"
  name                    = "${terraform.workspace}-subnet_public_2"
  vpc_id                  = module.v1.vpc_id
  cidr_block              = "10.0.2.0/24"
  map_public_ip_on_launch = false
  environment             = terraform.workspace
}

module "sn_priv_1" {
  source = "./modules/sn_priv_1"
  name                    = "${terraform.workspace}-subnet_private_1"
  vpc_id                  = module.v1.vpc_id
  cidr_block              = "10.0.101.0/24"
  map_public_ip_on_launch = false
  environment             = terraform.workspace
}

module "sn_priv_2" {
  source = "./modules/sn_priv_2"
  name                    = "${terraform.workspace}-subnet_private_2"
  vpc_id                  = module.v1.vpc_id
  cidr_block              = "10.0.102.0/24"
  map_public_ip_on_launch = false
  environment             = terraform.workspace
}

module "igw1" {
  source = "./modules/igw1"
  name        = "${terraform.workspace}-igw_main"
  vpc_id      = module.v1.vpc_id
  environment = terraform.workspace
}

module "nat1" {
  source = "./modules/nat1"
  name              = "${terraform.workspace}-nat_main"
  connectivity_type = "public"
  subnet_id         = module.sn_pub_1.subnet_id
  environment       = terraform.workspace

  depends_on = [module.igw1]
}

module "eks1" {
  source = "./modules/eks1"
  name              = "${terraform.workspace}-eks_cluster"
  cluster_version   = "1.29"
  region            = "us-east-1"
  compute_type      = "node_group"
  instance_type     = "t3.medium"
  desired_size      = 2
  min_size          = 2
  max_size          = 4
  cluster_role_name = "eks-cluster-role"
  environment       = terraform.workspace
  subnet_ids = [module.sn_priv_1.subnet_id, module.sn_priv_2.subnet_id]
}

module "lb_eks" {
  source = "./modules/lb_eks"
  name        = "${terraform.workspace}-alb_ingress"
  environment = terraform.workspace
  vpc_id             = module.v1.vpc_id
  security_group_ids = [module.sg_web.sg_id]
  target_port        = 80
  health_check_path  = "/health"
}

module "dns_eks" {
  source = "./modules/dns_eks"
  name        = "dominio_eks"
  domain_name = "k8s.exemplo.com"
  environment = terraform.workspace
}

module "st1" {
  source = "./modules/st1"
  name               = "${terraform.workspace}-s3_bucket"
  bucket_name        = "meu-bucket"
  versioning_enabled = true
  encryption_enabled = true
  environment        = terraform.workspace
}

module "lb1" {
  source = "./modules/lb1"
  name        = "${terraform.workspace}-load_balancer"
  environment = terraform.workspace
  vpc_id             = module.v1.vpc_id
  security_group_ids = [module.sg_web.sg_id]
  target_port        = 80
  health_check_path  = "/health"
}

module "sg_web" {
  source = "./modules/sg_web"
  name           = "${terraform.workspace}-sg_web"
  sg_description = "Managed by InfraPilot"
  vpc_id         = module.v1.vpc_id
  environment    = terraform.workspace
  ingress_rules = [
    { from_port = 80, to_port = 80, protocol = "tcp", cidr = "0.0.0.0/0", description = "HTTP" },
    { from_port = 443, to_port = 443, protocol = "tcp", cidr = "0.0.0.0/0", description = "HTTPS" }
  ]
  egress_rules  = [
    { from_port = 0, to_port = 0, protocol = "-1", cidr = "0.0.0.0/0", description = "All outbound" }
  ]
}

module "cw1" {
  source = "./modules/cw1"
  name               = "${terraform.workspace}-cloudwatch_monitoring"
  alarm_namespace    = "AWS/EC2"
  alarm_metric       = "CPUUtilization"
  alarm_threshold    = 80
  alarm_period       = 300
  alarm_eval_periods = 2
  environment        = terraform.workspace
}

